services:

    Dontdrinkandroot\AppIntegrationBundle\Security\AccessControlSubscriber:
        arguments:
            - '@security.authorization_checker'
        tags:
            - { name: 'kernel.event_subscriber' }
